version: "3.9"

services:
    postgres:
        image: postgres:16
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${FALCATA_DB}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        ports:
            - "5432:5433"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./WebServer/sql/iot.sql: /docker-entrypoint-initdb.d/01_iot.sql

volumes:
    pgdata:
